name: üîÅ Auto Playlist Generate (ZIP Protected)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/20 * * * *"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python libraries
        run: |
          pip install requests

      - name: Unlock ZIP (run unzipper.py)
        run: |
          python unzipper.py
        env:
          ZIP_PASSWORD: ${{ secrets.ZIP_PASSWORD }}

      - name: Run main playlist generator
        run: |
          python main/generate_playlist.py

      - name: Commit & Push playlist
        run: |
          git config --global user.name "Auto Bot"
          git config --global user.email "bot@example.com"
          git add playlist.m3u
          git commit -m "Auto update playlist" || echo "No changes"
          git push
